sudo: required

language: ruby

services:
    - docker

script:
  - sudo apt-get update
  - sudo apt-get install lxc-docker
  - scripts/tests.sh --build --verbose
  - scripts/tests.sh --run --verbose
